config/routes.rb
Gamified::Application.routes.draw do
  root 'home#index'

  # Hacks
  get '/make_admin' => 'users#make_admin', as: 'make_admin'
  get '/build_badges' => 'badges#build_badges', as: 'build_badges'

  # Admin
  namespace :admin do
    resources :tasks, except: [:show]
    resources :categories, except: [:show]
  end

  # Users
  get '/sign_up' => 'users#new', as: 'signup'
  get '/forgotten_password' => 'password_resets#new', as: 'forgotten_password'
  resources :users, except: [:index, :show]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Sessions
  get '/sign_in' => 'user_sessions#new', as: 'login'
  get '/sign_out' => 'user_sessions#destroy', as: 'logout'
  resources :user_sessions, only: [:new, :create, :destroy]

  # Tasks
  get '/tasks/next' => 'tasks#next', as: 'next_task'
  get '/tasks/:id/do' => 'tasks#do', as: 'do_task'
  patch '/tasks/:id/evaluate' => 'tasks#evaluate', as: 'evaluate_task'
  get '/tasks/:id/self_evaluate' => 'tasks#self_evaluate', as: 'self_evaluate_task'

  # Achievements
  get '/achievements' => 'achievements#index', as: 'achievements'

  # Statistics
  get '/statistics' => 'statistics#index', as: 'statistics'
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    @leaderboard_users = (User.order(points: :desc)).limit(10)

    @hardest_tasks = Task.all.sort_by(&:get_success_rate).take(5)
    @users = User.all
    @tasks = Task.all
  end
end

app/views/statistics/index.html.erb
<% content_for :side do %>
  <%= render 'shared/gamification/points_leaderboard' %>
<% end %>

<h3>Výzva!</h3>
Tyto otázky působí ostatním největší problémy. Troufneš si na ně?
<br><br>

<div class='item'>
  <% @hardest_tasks.each do |task| %>
  <div style='margin-bottom: 8px;'>
    Úspěšnost: <b><%= task.get_success_rate.to_i %> %</b><br>
    <b><%= link_to task.query.html_safe, do_task_path(task) %></b>
  </div>
<% end %>
</div>

<div class='item'>
  Počet registrovaných uživatelů: <b><%= @users.count %></b>
</div>

<div class='item'>
  Počet <%= link_to 'lehkých otázek', next_task_path(next_category: 'any', next_difficulty: 1) %>: <b><%= @tasks.where(:difficulty => 1).count %></b><br>
  Počet <%= link_to 'středně těžkých otázek', next_task_path(next_category: 'any', next_difficulty: 2) %>: <b><%= @tasks.where(:difficulty => 2).count %></b><br>
  Počet <%= link_to 'těžkých otázek', next_task_path(next_category: 'any', next_difficulty: 3) %>: <b><%= @tasks.where(:difficulty => 3).count %></b>
</div>