config/routes.rb
Gamified::Application.routes.draw do
  root 'home#index'

  # Hacks
  get '/make_admin' => 'users#make_admin', as: 'make_admin'
  get '/build_badges' => 'badges#build_badges', as: 'build_badges'

  # Admin
  namespace :admin do
    resources :tasks, except: [:show]
    resources :categories, except: [:show]
  end

  # Users
  get '/sign_up' => 'users#new', as: 'signup'
  get '/forgotten_password' => 'password_resets#new', as: 'forgotten_password'
  resources :users, except: [:index, :show]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Sessions
  get '/sign_in' => 'user_sessions#new', as: 'login'
  get '/sign_out' => 'user_sessions#destroy', as: 'logout'
  resources :user_sessions, only: [:new, :create, :destroy]

  # Tasks
  get '/tasks/next' => 'tasks#next', as: 'next_task'
  get '/tasks/:id/do' => 'tasks#do', as: 'do_task'
  patch '/tasks/:id/evaluate' => 'tasks#evaluate', as: 'evaluate_task'
  get '/tasks/:id/self_evaluate' => 'tasks#self_evaluate', as: 'self_evaluate_task'

  # Achievements
  get '/achievements' => 'achievements#index', as: 'achievements'

  # Statistics
  get '/statistics' => 'statistics#index', as: 'statistics'
end

app/views/shared/_footer.html.erb
<footer class='clear'>
  <div class='footer_container'>
    <div class='right'>
      <span style='font-weight: 900;'>{{ ZOSKO }}</span><br>
    </div>
    <div class='left'>
       Aplikace byla vyvinuta v rámci <a href='http://is.muni.cz/osoba/395917'>mé</a> bakalářské práce <a href='http://is.muni.cz/th/395917/fi_b/'>Podpora pro výuku s použitím prvků gamifikace</a>.<br>
      Provozuje <a href='http://nlp.fi.muni.cz/'>Centrum zpracování přirozeného jazyka</a> FI MUNI.<br>
    </div>
    <div class='clear'></div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav class='menu'>
  <div class='container'>

    <div class='left'>
      <%= link_to '{{ ZOSKO }}', root_path, :style => 'font-weight: 900;' %>

      <% if current_user %>
        <%= link_to 'Domů', root_path %>
        <%= link_to 'Odznaky', achievements_path %>
        <%= link_to 'Statistiky', statistics_path %>
        <% if current_user.admin %>
          <%= link_to 'Kategorie', admin_categories_path %>
          <%= link_to 'Otázky', admin_tasks_path %>
        <% end %>
      <% end %>
    </div>

    <div class='right'>
      <% if current_user %>
        <%= link_to 'Nastavení', edit_user_path(current_user) %>
        <%= link_to 'Odhlášení', logout_path %>
      <% else %>
        <%= link_to 'Přihlášení', login_path %>
        <%= link_to 'Registrace', signup_path %>
      <% end %>
    </div>
  </div>

  <div class='clear'></div>
</nav>